prefix = "."
dataset = "train_news"
corpus = "line.toml"
index = "train_idx"
stop-words = "lemur-stopwords.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = [{type = "icu-tokenizer", suppress-tags = true}, {type = "lowercase"}, {type = "length", min = 2, max = 30}]
